jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache Maven Repository
      uses: actions/cache@v1
      with:
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2
        restore-keys: ${{ runner.os }}-m2
    - continue-on-error: true
      name: mvn verify
      run: mvn verify -Dnosign
    strategy:
      matrix:
        java:
        - '11'
        - '17'
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
